### ISSUE TITLE
installMaGe fails during compilation of MaGe files

### ISSUE THREAD

**Issue by luigiberducci** [legend-exp/legend-swdev-scripts#2]
Running the script `installMaGe.py` in Legend Docker Container (https://github.com/legend-exp/legendexp_legend-base_img) to build MGDO, MaGe and GAT, an error occurs during the compilation of MaGe files. As a consequence, I cannot complete the installation of MaGe.

I run the container on Linux Ubuntu 18.04 with the following commands:
```
docker pull legendexp/legend-base:latest
docker run -it  -v "$HOME":"/home/user":consistent -v "${HOME}/legend-base":"/root":delegated \  
          -p 8888:8888 -p 14500:14500 legendexp/legend-base:latest
```
Then, I copied the `installMaGe.py` script in ${HOME}/legend-base and run the following commands from within the container:
```
mkdir dirinstall
python /root/installMaGe.py /root/dirinstall/
source /root/setup_mage.sh
python /root/installMaGe.py /root/dirinstall/
```
When it starts compiling the MaGe files, the following error occurs:
```
Compiling MGImportanceAlgorithm.cc ...
src/MGImportanceAlgorithm.cc: In member function 'virtual G4Nsplit_Weight MGImportanceAlgorithm::Calculate(G4double, G4double, G4double) const':
src/MGImportanceAlgorithm.cc:87:28: error: could not convert '{0, 0}' from '<brace-enclosed initializer list>' to 'G4Nsplit_Weight'
   G4Nsplit_Weight nw = {0,0};
                            ^
make[1]: *** [/root/MaGe/tmp/Linux-g++/geometry/MGImportanceAlgorithm.o] Error 1
make: *** [geometry] Error 2
Entering directory geometry
make[1]: Entering directory `/root/MaGe/geometry'
Compiling MGImportanceAlgorithm.cc ...
src/MGImportanceAlgorithm.cc: In member function 'virtual G4Nsplit_Weight MGImportanceAlgorithm::Calculate(G4double, G4double, G4double) const':
src/MGImportanceAlgorithm.cc:87:28: error: could not convert '{0, 0}' from '<brace-enclosed initializer list>' to 'G4Nsplit_Weight'
   G4Nsplit_Weight nw = {0,0};
                            ^
make[1]: *** [/root/MaGe/tmp/Linux-g++/geometry/MGImportanceAlgorithm.o] Error 1
make[1]: Leaving directory `/root/MaGe/geometry'
make: *** [install] Error 2
```

The complete log file is attached.
[install.log](https://github.com/legend-exp/legend-swdev-scripts/files/4306052/install.log)

**Comment by oschulz** [comment]
@mpgreen, could you take a look at this? I guess this is due to the new Geant4 10.6 in the container (that I updated to for G4TENDL). If MaGe is not compatible with 10.6, should we go back to 10.5, temporarily?

**Comment by luigiberducci** [comment]
I loaded a previous version (1 month ago) of the docker image, with Geant4 10.5 and it works well.

**Comment by luigiberducci** [comment]
However, when I run MaGe on a macro sample (the copy "testCR_LGND.txt" is attached), I still receive an error and the run aborts.
The error is the following:
```

-------- EEEE ------- G4Exception-START -------- EEEE -------
*** G4Exception : de0001
      issued by : G4AtomicTransitionManager::Shell()
No de-excitation for Z= 7  shellIndex= 0. AtomicShell not found - check if data are uploaded

*** Fatal Exception *** core dump ***
G4Track (0x30e98660) - track ID = 9509, parent ID = 9464
 Particle type : O15 - creator process : neutronInelastic, creator model : Undefined
 Kinetic energy : 0 eV  - Momentum direction : (-0.318389,-0.930573,0.180727)
 Step length : 0 fm  - total energy deposit : 0 eV 
 Pre-step point : (20891.4,43676.3,-80500.8) - Physical volume : cavern (Rock)
 - defined by : ionIoni - step status : 3
 Post-step point : (20891.4,43676.3,-80500.8) - Physical volume : cavern (Rock)
 - defined by : ionIoni - step status : 7
 *** Note: Step information might not be properly updated.

-------- EEEE -------- G4Exception-END --------- EEEE -------


*** G4Exception: Aborting execution ***
```
The complete log file "mage.log" is attached.

I don't know if it is related to Geant4 or there is something missing in the installation.

[mage.log](https://github.com/legend-exp/legend-swdev-scripts/files/4310828/mage.log)

[testCR_LGND.txt](https://github.com/legend-exp/legend-swdev-scripts/files/4310831/testCR_LGND.txt)

**Comment by luigiberducci** [comment]
The last problem is not related to the installation of MaGe, so I close the issue.

Probably it is related to G4 and the physics process simulated. In fact, changing the seed the simulation goes smoothly, then there is some event that is handled badly...
